### PR TITLE
[Liquidation Bot] Liquidator delay option & some other minor stuff

### PR DESCRIPTION
**Pull request by Alexsey**
* Add support for TRADERS_LIQUIDATOR_DELAY_SEC parameter that would allow to slow down our bot in order for it not to challenge with other bots but only to ensure that traders would be liquidated even if no external bots would be running
* change some `| undefined` to `:?` in types for a better way to represent optional parameters. Also, it is more laconically
* retry interval fix. Due to a bug it was 1000 times less than expected. Considered as ignored

---
This change is [Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/27)

### CODE REVIEW

**Review by ilya-bobyr — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/27)* status: all files reviewed, 2 unresolved discussions (waiting on @Alexsey)

___
*[src/liquidationBot/index.ts, line 18 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/27#-Murx5vC2IwcE3dPG3xB:-Murx5vC2IwcE3dPG3xC:bnkimi) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bda224945956579a92ab8995756617025c1550b3/src/liquidationBot/index.ts#L18)):*
> ```XML
> import { IExchangeEvents } from "@generated/IExchangeEvents";
> 
> type LiquidationBotKeys<T = {}> = T & {
> ```

I am not 100% sure that using `?` here conveys the right intent.
All these fields are valid arguments.
But we may not have a value at a certain point, as it could be coming from the `.env` file or from the default value.
Not sure if any can be completely omitted.
` | undefined` is used when the value might not be available just yet.
`?:` removes the field from the data structure, IIUC.


I am also not a big fan of `?:`, as it moves part of the type definition away from the rest of it.
But, maybe, I am just not used to this particular TypeScript pattern.



_Code quote:_
```XML
type LiquidationBotKeys<T = {}> = T & {
  "liquidation-bot"?: string;
  "exchange-launch-block"?: number;
  "max-blocks-per-json-rpc-query"?: number;
  "refetch-interval"?: number;
  "recheck-interval"?: number;
  "liquidation-retry-interval"?: number;
  "liquidation-delay"?: number;
  "max-traders-per-liquidation-check"?: number;
  reporting?: string;
};
```
___
*[src/liquidationBot/index.ts, line 95 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/27#-Mur03vX2lXVIE3lnuZg:-Mur03vX2lXVIE3lnuZh:b-ueht7q) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bda224945956579a92ab8995756617025c1550b3/src/liquidationBot/index.ts#L95)):*
> ```XML
>         "liquidate it. In seconds.\n" +
>         "Setting this parameter to a non-zero value would make your bot\n" +
>         "significantly less compatible!\n" +
> ```

s/compatible/competitive/

**Comment by Alexsey** [comment]
___
*[src/liquidationBot/index.ts, line 18 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/27#-Murx5vC2IwcE3dPG3xB:-Muw2Ei6Dj6qyF4XfUlo:bjdmhoy) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bda224945956579a92ab8995756617025c1550b3/src/liquidationBot/index.ts#L18)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

I am not 100% sure that using `?` here conveys the right intent.
All these fields are valid arguments.
But we may not have a value at a certain point, as it could be coming from the `.env` file or from the default value.
Not sure if any can be completely omitted.
` | undefined` is used when the value might not be available just yet.
`?:` removes the field from the data structure, IIUC.


I am also not a big fan of `?:`, as it moves part of the type definition away from the rest of it.
But, maybe, I am just not used to this particular TypeScript pattern.
</blockquote></details>

I agree with you so this commit has been removed

**Comment by Alexsey** [comment]
___
*[src/liquidationBot/index.ts, line 95 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/27#-Mur03vX2lXVIE3lnuZg:-Muw5O4XD0L6S5CZoGp6:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bda224945956579a92ab8995756617025c1550b3/src/liquidationBot/index.ts#L95)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

s/compatible/competitive/
</blockquote></details>

Done.

**Review by ilya-bobyr — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alexsey)

**Pull request merged**
