### PR TITLE
Update Liquidation bot CLI to use Arbitrum RPC provider instead of hosted trade indexer

### PR DESCRIPTION
**Pull request by kienswap**
This change is [Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)

### CODE REVIEW

**Review by kienswap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[README.md, line 69 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwCaYT5GuiXV-xKUed:-MqwCaYT5GuiXV-xKUee:bwbeocy) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/073939ae16967bd966d9bc7949632c19bb0db8ff/README.md#L69)):*
> ```Markdown
> EXCHANGE_ADDRESS=0x1B5A08020E94066a3fB91Aff8B395De2d9cfaDd2
> ```
> ```

These empty spaces are added by "yarn format"

**Review by ilya-bobyr — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @kienswap and @maxibustos)

___
*[.gitignore, line 6 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwiXN3EvoIQ1u2H4T8:-MqwiXN3EvoIQ1u2H4T9:b1heevz) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/.gitignore#L6)):*
> ```
> # IDEA-specific configs.
> .idea
> ```

This should be in your user .gitignore.
It should not go into the project wide one.

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

https://git-scm.com/docs/gitignore

So, add it to your `$HOME/.config/git/ignore` instead.
___
*[README.md, line 124 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwjFqw1lFYRUKdmntS:-MqwjFqw1lFYRUKdmntT:bkncwbc) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/README.md#L124)):*
> ```
> yarn start liquidationBot --networkId <ARBITRUM_RINKEBY|ARBITRUM> \
>     --exchangeAddress <exchange_address>
> ```

We use `RINKEBY_ARBITRUM` and `MAINNET_ARBITRUM` in our internal repo.
I have a change to do the same for the open source one.
___
*[src/config/config.ts, line 13 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwjTzWB7wqCtz9YVD8:-MqwjTzWB7wqCtz9YVD9:b9fkr5e) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/config/config.ts#L13)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   readonly network: {
>     readonly mnemonic: string;
>     readonly chainId: number;
>     readonly rpcUrl: string;
>     readonly address: string;
>     readonly exchangeGenesisBlock: number;
>   };
> ```
</details>


`network` is related to the JSON-RPC configuration.
`address` got there by accident.
Not sure that `exchangeGenesisBlock` fits in there.
I would put it next to `exchangeAddress`.
___
*[src/config/config.ts, line 20 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwkiUT4rAyA54w5jZp:-MqwkiUT4rAyA54w5jZq:buh4bnx) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/config/config.ts#L20)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   readonly liquidationBot: {
>     readonly maxBlocksToProcessPerRound: number;
>     readonly maxTradersPerLiquidatableCheck: number;
>   };
> ```
</details>


`liquidationBot` section is related to the `LiquidationBotApi` interaction.
Though, the current layout is confusing.

Also `maxBlocksToProcessPerRound` is very generic.
I would call it `maxBlocksPerJsonRpcQuery` or something like that.

This property is one of the `tradersFetcher` parameters, so it should probably go into `processors.tradersFetcher`.
But again, I have a change that reorganizes the config completely.
___
*[src/liquidationBot/services/exchange/exchange.ts, line 38 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mqwm2xNAhVsVv8tVEr-:-Mqwm2xNAhVsVv8tVEr0:b-abvwbq) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/liquidationBot/services/exchange/exchange.ts#L38)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
>   const blockRangesToProcess = [];
>   // Process blocks in smaller batches to avoid hitting the provider's limit.
>   for (
>     let rangeStart = startBlock;
>     rangeStart < currentBlockNumber;
>     rangeStart += rangeSize
>   ) {
>     blockRangesToProcess.push([
>       rangeStart,
>       Math.max(rangeStart + rangeSize, currentBlockNumber),
>     ]);
>   }
> 
>   const lastTraderActions: LastTraderActions = {};
>   for (const [startBlock, endBlock] of blockRangesToProcess) {
>     const changePositionsEvents = await exchangeEventsApi.queryFilter(
>       eventFilter,
>       startBlock,
>       endBlock
>     );
> ```
</details>


I think these two loops can be combined.
And `blockRangesToProcess` is then unnecessary.

**Review by ilya-bobyr — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: all files reviewed, 6 unresolved discussions (waiting on @kienswap and @maxibustos)

**Review by kienswap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: 2 of 36 files reviewed, 6 unresolved discussions (waiting on @ilya-bobyr and @maxibustos)

___
*[.gitignore, line 6 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwiXN3EvoIQ1u2H4T8:-Mqzh9NFA07r7o-mYkze:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/.gitignore#L6)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
> # IDEA-specific configs.
> .idea
> ```

This should be in your user .gitignore.
It should not go into the project wide one.

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

https://git-scm.com/docs/gitignore

So, add it to your `$HOME/.config/git/ignore` instead.
</blockquote></details>

Done.
___
*[README.md, line 124 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwjFqw1lFYRUKdmntS:-MqzgxvW10111ReqlCKO:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/README.md#L124)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
> yarn start liquidationBot --networkId <ARBITRUM_RINKEBY|ARBITRUM> \
>     --exchangeAddress <exchange_address>
> ```

We use `RINKEBY_ARBITRUM` and `MAINNET_ARBITRUM` in our internal repo.
I have a change to do the same for the open source one.
</blockquote></details>

Done.
___
*[src/config/config.ts, line 13 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwjTzWB7wqCtz9YVD8:-Mqzh0yj3XKhQzIF3jyo:b-cnltmk) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/config/config.ts#L13)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
>   readonly network: {
>     readonly mnemonic: string;
>     readonly chainId: number;
>     readonly rpcUrl: string;
>     readonly address: string;
>     readonly exchangeGenesisBlock: number;
>   };
> ```

`network` is related to the JSON-RPC configuration.
`address` got there by accident.
Not sure that `exchangeGenesisBlock` fits in there.
I would put it next to `exchangeAddress`.
</blockquote></details>

Updated after rebasing to your changes.
___
*[src/config/config.ts, line 20 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqwkiUT4rAyA54w5jZp:-Mqzh58F1rA0kJZYHQMt:b2zv0oc) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/config/config.ts#L20)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
>   readonly liquidationBot: {
>     readonly maxBlocksToProcessPerRound: number;
>     readonly maxTradersPerLiquidatableCheck: number;
>   };
> ```

`liquidationBot` section is related to the `LiquidationBotApi` interaction.
Though, the current layout is confusing.

Also `maxBlocksToProcessPerRound` is very generic.
I would call it `maxBlocksPerJsonRpcQuery` or something like that.

This property is one of the `tradersFetcher` parameters, so it should probably go into `processors.tradersFetcher`.
But again, I have a change that reorganizes the config completely.
</blockquote></details>

Done. Rebased to your changes.
___
*[src/liquidationBot/services/exchange/exchange.ts, line 38 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mqwm2xNAhVsVv8tVEr-:-MqzhAe93KZqyCquvaTG:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/0587cb982040e628778acd762b964a6a35c005d4/src/liquidationBot/services/exchange/exchange.ts#L38)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
>   const blockRangesToProcess = [];
>   // Process blocks in smaller batches to avoid hitting the provider's limit.
>   for (
>     let rangeStart = startBlock;
>     rangeStart < currentBlockNumber;
>     rangeStart += rangeSize
>   ) {
>     blockRangesToProcess.push([
>       rangeStart,
>       Math.max(rangeStart + rangeSize, currentBlockNumber),
>     ]);
>   }
> 
>   const lastTraderActions: LastTraderActions = {};
>   for (const [startBlock, endBlock] of blockRangesToProcess) {
>     const changePositionsEvents = await exchangeEventsApi.queryFilter(
>       eventFilter,
>       startBlock,
>       endBlock
>     );
> ```

I think these two loops can be combined.
And `blockRangesToProcess` is then unnecessary.
</blockquote></details>

Done.

**Review by ilya-bobyr — APPROVED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: all files reviewed, 5 unresolved discussions (waiting on @kienswap and @maxibustos)

___
*[src/liquidationBot/bot.ts, line 87 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mqzu91nA74Zeb2GRYFJ:-Mqzu91nA74Zeb2GRYFK:b1r527x) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/bot.ts#L87)):*
> ```XML
>   exchangeEvents: IExchangeEvents,
>   liquidationBotApi: LiquidationBotApi,
>   startBlock: number,
> ```

`startBlock` is a bit too generic, considering it is a configuration parameter.
`exchangeLaunchBlock`?
___
*[src/liquidationBot/index.ts, line 33 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqzwZY80mK1XSc78q1k:-MqzwZY80mK1XSc78q1l:b-hoir0b) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/index.ts#L33)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // These are the blocks containing the first transactions to the first exchange.
> const FUTURESWAP_EXCHANGE_GENESIS_BLOCKS: { [network: string]: number } = {
>   RINKEBY_ARBITRUM: 5280847,
>   MAINNET_ARBITRUM: 2194550,
> };
> ```
</details>


It does not take the exchange into consideration.
We can always go all the way back to the very first exchange on each network.
But maybe there is a better solution.
For example, we could instead use the exchange address as the key.
Or both the network and the exchange address.

We can probably keep it like this for now.
But something to think about.
I would add a comment explaining this limitation, at least.

We are at a point when we need to start thinking about multi-exchange support.
And any code that does not, will need work.
___
*[src/liquidationBot/index.ts, line 55 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqztL706agx1L_rqq0Y:-MqztL715xQD2leYj8Ss:bllfuvg) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/index.ts#L55)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```typescript
>     .option("start-block", {
>       describe:
>         "Arbitrum block to start scanning traders from for liquidation" +
>         `Defaults to: ${FUTURESWAP_EXCHANGE_GENESIS_BLOCKS}`,
> ```
</details>



`FUTURESWAP_EXCHANGE_GENESIS_BLOCKS` is an object.
So this is probably not showing a very helpful default value.
In an option above, I've just said:

```typescript
"Default depends on the chosen network."
```
___
*[src/liquidationBot/__tests__/integration/liquidationBot.test.ts, line 165 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqzxPzI-PHDzhopBGmw:-MqzxPzI-PHDzhopBGmx:b-xbtwdu) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/__tests__/integration/liquidationBot.test.ts#L165)):*
> ```XML
>     start();
>     await onceBotEvent("tradersChecked");
>     await onceBotEvent("tradersFetched"); // some long waining
> ```

Do not understand the comment.
Is the test slow?

**Review by kienswap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: all files reviewed, 5 unresolved discussions (waiting on @ilya-bobyr and @maxibustos)

___
*[src/liquidationBot/bot.ts, line 87 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mqzu91nA74Zeb2GRYFJ:-MqzyuefCQe7HeKpa7XF:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/bot.ts#L87)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

`startBlock` is a bit too generic, considering it is a configuration parameter.
`exchangeLaunchBlock`?
</blockquote></details>

Done.
___
*[src/liquidationBot/index.ts, line 33 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqzwZY80mK1XSc78q1k:-Mqzyv6X8W62u5E4FVRh:blz4w02) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/index.ts#L33)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
> // These are the blocks containing the first transactions to the first exchange.
> const FUTURESWAP_EXCHANGE_GENESIS_BLOCKS: { [network: string]: number } = {
>   RINKEBY_ARBITRUM: 5280847,
>   MAINNET_ARBITRUM: 2194550,
> };
> ```

It does not take the exchange into consideration.
We can always go all the way back to the very first exchange on each network.
But maybe there is a better solution.
For example, we could instead use the exchange address as the key.
Or both the network and the exchange address.

We can probably keep it like this for now.
But something to think about.
I would add a comment explaining this limitation, at least.

We are at a point when we need to start thinking about multi-exchange support.
And any code that does not, will need work.
</blockquote></details>

Yeah I thought about this as well. What do you mean by using exchange address as the key? Are you talking about having the ChangePositionEvents indexed by exchange address? I noticed it's currently not indexed by any field. 
___
*[src/liquidationBot/index.ts, line 55 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqztL706agx1L_rqq0Y:-MqzzPVlBKuo11RvPfR4:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/index.ts#L55)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```typescript
>     .option("start-block", {
>       describe:
>         "Arbitrum block to start scanning traders from for liquidation" +
>         `Defaults to: ${FUTURESWAP_EXCHANGE_GENESIS_BLOCKS}`,
> ```


`FUTURESWAP_EXCHANGE_GENESIS_BLOCKS` is an object.
So this is probably not showing a very helpful default value.
In an option above, I've just said:

```typescript
"Default depends on the chosen network."
```
</blockquote></details>

Done.
___
*[src/liquidationBot/__tests__/integration/liquidationBot.test.ts, line 165 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqzxPzI-PHDzhopBGmw:-MqzzQtWBwaRwgU2ec3j:b-jckpsq) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/__tests__/integration/liquidationBot.test.ts#L165)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

Do not understand the comment.
Is the test slow?
</blockquote></details>

Probably but I have no idea either. I honestly think this comment is useless as it doesn't point out a solution for making the tests faster. I'll delete them.

**Review by ilya-bobyr — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: all files reviewed, 3 unresolved discussions (waiting on @kienswap and @maxibustos)

___
*[src/liquidationBot/index.ts, line 33 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-MqzwZY80mK1XSc78q1k:-Mr-cdKTBMcik3KXgq7p:blvxa8t) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4075e7164014e4439341782e3bb49852854865ed/src/liquidationBot/index.ts#L33)):*
<details><summary><i>Previously, kienswap wrote…</i></summary><blockquote>

Yeah I thought about this as well. What do you mean by using exchange address as the key? Are you talking about having the ChangePositionEvents indexed by exchange address? I noticed it's currently not indexed by any field. 
</blockquote></details>

Yes, using exchange address as a key to pick the default.
We can submit this as is, and look into it later.
But if we have some ideas already, we could also add a comment explaining them.

ChangePositionEvents is generated for our exchange contract.
So it is connected to the exchange address.
You do this implicitly in the code, as you call `queryFilter` on the exchange contract object.
It is possible to query for events without limiting results to a certain contract: https://docs.ethers.io/v5/api/providers/provider/#Provider-getLogs

---

This is a discussion.
It does not block the PR.
___
*[src/liquidationBot/types.ts, line 6 at r4](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mr-dUdA2rbVQbweseH9:-Mr-dUdA2rbVQbweseHA:b-85m62) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/9dfc67104e5cc9c7cf07b04fd245b331c6a837d8/src/liquidationBot/types.ts#L6)):*
> ```
>   OPEN_POSITION,
>   CLOSE_POSITION,
> ```

Common style is to use CapitalCase for enumeration member names, not snake upper case.
They are treated as constructors.
___
*[src/liquidationBot/__tests__/integration/liquidationBot.test.ts, line 45 at r4](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mr-djjhD6J6Rv6trXX5:-Mr-djji3FsDa8sYEk9I:bek5zce) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/9dfc67104e5cc9c7cf07b04fd245b331c6a837d8/src/liquidationBot/__tests__/integration/liquidationBot.test.ts#L45)):*
> ```
>   // TODO `as any as Type` conversion is not safe.  It would be nice to replace it with a more
>   // comprehensive mock.  One that would through a meaningful error if an unexpected property is
>   // accessed, for example.
> ```

_minor_

This comment was at the beginning of the function, as it applies to all the `as any as Type` conversions that come after it.
Now it actually follows a few of these conversions.

**Review by kienswap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/12)* status: 9 of 35 files reviewed, 3 unresolved discussions (waiting on @ilya-bobyr, @kienswap, and @maxibustos)

___
*[src/liquidationBot/types.ts, line 6 at r4](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mr-dUdA2rbVQbweseH9:-Mr0FYzE1VS9FbIIaGTN:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/9dfc67104e5cc9c7cf07b04fd245b331c6a837d8/src/liquidationBot/types.ts#L6)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
>   OPEN_POSITION,
>   CLOSE_POSITION,
> ```

Common style is to use CapitalCase for enumeration member names, not snake upper case.
They are treated as constructors.
</blockquote></details>

Done.
___
*[src/liquidationBot/__tests__/integration/liquidationBot.test.ts, line 45 at r4](https://reviewable.io/reviews/futureswap/fs-cli-v4/12#-Mr-djjhD6J6Rv6trXX5:-Mr0F_N245LqXW7HJDYc:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/9dfc67104e5cc9c7cf07b04fd245b331c6a837d8/src/liquidationBot/__tests__/integration/liquidationBot.test.ts#L45)):*
<details><summary><i>Previously, ilya-bobyr (Ilya Bobyr) wrote…</i></summary><blockquote>

> ```
>   // TODO `as any as Type` conversion is not safe.  It would be nice to replace it with a more
>   // comprehensive mock.  One that would through a meaningful error if an unexpected property is
>   // accessed, for example.
> ```

_minor_

This comment was at the beginning of the function, as it applies to all the `as any as Type` conversions that come after it.
Now it actually follows a few of these conversions.
</blockquote></details>

Done.

**Pull request merged**
