### PR TITLE
Extract config

### PR DESCRIPTION
**Pull request by ilya-bobyr**
---

This PR is a combination of multiple commits, each of which should make sense on its own.
I could send them as individual PRs, but most of them rely on each other.
You probably want to switch to a review mode where you review individual commits, instead of reviewing the whole PR as one big change.

---
This change is [Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/13)

### CODE REVIEW

**Review by kienswap — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/13)* status: 3 of 32 files reviewed, 1 unresolved discussion (waiting on @Alexsey, @ilya-bobyr, and @kienswap)

___
*[src/config/utils.ts, line 53 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/13#-MqyJvHL79NW_q0IPQdg:-MqyJvHL79NW_q0IPQdh:b-9lx4jz) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/41c900cf85483d0cf47ed9f74b111d06215f3625/src/config/utils.ts#L53)):*
> ```XML
> ): AllowedValue | (Opts extends { isOptional: true } ? undefined : never) {
>   const { isOptional } = opts;
>   const value = process.env[envVarName];
> ```

nit: Can this be simplified as const value = process.env[envVarName] || opts.default;

if (value === undefined && !iOptional) {
   throw....
}

return value;

**Review by kienswap — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 18 of 18 files at r7, 1 of 1 files at r8, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/13)* status: all files reviewed, 2 unresolved discussions (waiting on @Alexsey and @ilya-bobyr)

___
*[src/index.ts, line 48 at r6](https://reviewable.io/reviews/futureswap/fs-cli-v4/13#-MqyNd2sCOv-mfMib4jo:-MqyNd2sCOv-mfMib4jp:bt066ij) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4e34ecb47402c6c8e1000f7a4da035bf7af8a191/src/index.ts#L48)):*
> ```XML
> 
> export type WithProviderArgs<T = {}> = WithNetworkArgs<T>;
> const withProviderArgv = withNetworkArgv;
> ```

Why is withNetworkArgv used directly instead of indirectly through withProviderArgv?

**Review by kienswap — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/13#-:-Mr-0u8QAK_0vFClNPhz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alexsey and @ilya-bobyr)

**Review by ilya-bobyr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/13)* status: 4 of 32 files reviewed, 2 unresolved discussions (waiting on @Alexsey and @kienswap)

___
*[src/index.ts, line 48 at r6](https://reviewable.io/reviews/futureswap/fs-cli-v4/13#-MqyNd2sCOv-mfMib4jo:-Mr-xknO1PkpmG-aQKab:bewp6b5) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/4e34ecb47402c6c8e1000f7a4da035bf7af8a191/src/index.ts#L48)):*
<details><summary><i>Previously, kienswap wrote…</i></summary><blockquote>

Why is withNetworkArgv used directly instead of indirectly through withProviderArgv?
</blockquote></details>

I am still experimenting, but the intent is to find a patter that would help with sharing of the common code for argument parsing between the CLI commands.
We have a lot of commands and the number is only increasing.

At the same time, they have groups of arguments that should be processed identically between different commands.
Yet, they do not completely overlap.
But, these groups do overlap and form some kind of classes.
For example, a command that will perform a state changing operation on the exchange needs the same parameters as the one that just interacts with the JSON-RPC provider.

So, right now, every group is described using the following:
1. A function that extends the `yargs` object with all the arguments of this group.  This function is called `<fooBar>Argv`.
2. Type of the fields the `<fooBar>Argv` adds to `yargs`.  This type is needed to construct functions that extend `<fooBar>Argv`.  It is called `<FooBar>Args`.
3. Function that processes arguments parsed by `yargs` into internal representation.  It is called `get<fooBar>.
4. Type of the `yargs` object that the `get<fooBar>` consumes.  Again, used to construct derived functions.  It is called `Get<FooBar>Argv`.

The above is not complete, as it also needs explicit types for the `get<fooBar>` returned object.
Maybe I'll add it later.  Or maybe there is a better way to describe all this, using some of the type level helpers that TypeScript provides.

Also, in a few cases, I've used `with<fooBar>Argv` and `With<FooBar>Args` for items 1 and 2.
I'm still trying to find a good compromise between readability and noise here.

In this particular case, `getProvider` uses the same arguments as `getNetwork`.
Some commands do not need a provider, but do need a network.
`WithProviderArgs` and `WithNetworkArgs`, as well as `withProviderArgv` and `withNetworkArgv` are therefore the same.
But following the pattern I need to have them defined nevertheless.
___
*[src/config/utils.ts, line 53 at r3](https://reviewable.io/reviews/futureswap/fs-cli-v4/13#-MqyJvHL79NW_q0IPQdg:-Mr0-SqnAwxL4fyEePnS:blgwkhc) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/41c900cf85483d0cf47ed9f74b111d06215f3625/src/config/utils.ts#L53)):*
<details><summary><i>Previously, kienswap wrote…</i></summary><blockquote>

nit: Can this be simplified as const value = process.env[envVarName] || opts.default;

if (value === undefined && !iOptional) {
   throw....
}

return value;
</blockquote></details>

True.
For the case when we read from both `yargs` and `process.env` it is more complex.
So it no longer applies.
Also, simpler checks are easier to read =)

**Pull request merged**
