### PR TITLE
CLI: `exchange update-indentives` command

### PR DESCRIPTION
**Pull request by ilya-bobyr**
We need to run this after every ADL.

---
This change is [Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/28)

### CODE REVIEW

**Review by Alexsey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/28)* status: 0 of 16 files reviewed, 11 unresolved discussions (waiting on @Alexsey and @ilya-bobyr)

___
*[src/exchange.ts, line 217 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJS2fE76yhcFEt-ipN:-MvJS2fE76yhcFEt-ipO:b-2l1oqk) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange.ts#L217)):*
> ```XML
>   }
> 
>   const default_ = deployment.launchBlock;
> ```

`default_` seems redundant here - changing below to `{ default: deployment.launchBlock }` would look even more informative
___
*[src/config/deployments.ts, line 1 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIkRw37_yjA3pW3EwE:-MvIkRw37_yjA3pW3EwF:bmklvj) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L1)):*
> ```XML
> /**
> ```

What is the reason for constructing this config half-programmatically and half-manually? It really looks like that simple structure, like the one that has been used before, would suit much better
```ts
export const deployments = {
  RINKEBY_ARBITRUM: {
    ETH_USDC: {
      exchangeAddress: "...",
      launchBlock: 123,
    },
    ....
  }
}
```
Just ensure `Deployments` to have methods `get` and `addresses`. And yes, the presence of `get` method seems like an opportunity to use pairs names as keys, that are simpler and more representative then addresses (would look much nicer in logs).
___
*[src/config/deployments.ts, line 10 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIq-_M5DclgCVBv2yi:-MvImoewA6cLnaeL3RcD:bul07ax) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L10)):*
> ```XML
>  * Described properties of a single deployment.
>  */
> export class DeploymentInfo {
> ```

Looks like this can be a simpler `type` instead of `class`.
___
*[src/config/deployments.ts, line 26 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvImEh4-DXmh30-0LCp:-MvImEh4-DXmh30-0LCq:bg53ymd) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L26)):*
> ```XML
>   constructor(
>     /// Maps exchange addresses to corresponding deployment information.
>     public deployemnts: Map<string, DeploymentInfo>
> ```

It's always preferable to use plan object instead of `Map<string, whatever>` as one is more basic and much easier to work with data structures.
___
*[src/config/deployments.ts, line 41 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvImIpU5Qo-Uc_ZPGTA:-MvImIpU5Qo-Uc_ZPGTB:b-1x8oc9) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L41)):*
> ```XML
> 
>   public addresses(): string[] {
>     return [...this.deployemnts.keys()];
> ```

This is the same as `return this.deployments.keys()`.
___
*[src/config/deployments.ts, line 46 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIn70s1HRBiZR0sR8x:-MvIn70s1HRBiZR0sR8y:b-l4m4oj) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L46)):*
> ```XML
> 
> export const deployments: {
>   [network: string]: Deployments;
> ```

It's better to avoid setting a type here - TypeScript itself would produce a better more specific type with keys limited to the actual values you've used. Unless you want it to be more generic with `string` as a key on purpose.
___
*[src/exchange/positions.ts, line 13 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIoxpU-GQq2riQQx4s:-MvIoxpU-GQq2riQQx4t:b5fbfxq) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L13)):*
> ```XML
> import { tryNTimes } from "utils";
> 
> enum PositionState {
> ```

```ts
type PositionState = Brand<"open" | "close", "positionState">
```
or IMHO absolutely good enough as for a non-public type
```ts
type PositionState = "open" | "closed"
```
would be a simpler structure that would feet the needs as well as `enum` but without adding any code to the runtime
___
*[src/exchange/positions.ts, line 18 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIoVNz1Pv4jtW-O5pW:-MvIoVNz1Pv4jtW-O5pX:bl7sbq3) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L18)):*
> ```XML
> }
> 
> export class Position {
> ```

It looks like this can by `type` instead of `class`.
___
*[src/exchange/positions.ts, line 40 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvInzNb8OGli1R3FOwn:-MvInzNb8OGli1R3FOwo:bwtwc3q) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L40)):*
> ```XML
> export class Positions {
>   constructor(
>     public positions: Map<string, Position> = new Map<string, Position>(),
> ```

It's always preferable to use a plan object instead of `Map<string, whatever>` as one is more basic and much easier to work with data structures.
___
*[src/exchange/positions.ts, line 110 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJKG7t9i5QcwAeLH_Z:-MvJKG7t9i5QcwAeLH__:bvzjwmw) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L110)):*
> ```XML
>         break;
> 
>       default:
> ```

Currently `default` branch is impossible. I assume that you've added it in case of other possible values would be added to `PositionState`. You can ask the compiler to give an error if `PositionState` would be extended without adding a `case` to handle that new values. There are two ways to do this: first is a more general pattern that would allow to left `updateStats` signature as is (exhaustive switch), but I think we can go have with a simpler one
```ts
private updateStats(...): number {
    state: PositionState,
    update: (counter: number) => number
  ) {
    switch (state) {
      case PositionState.Open:
        return this.stats.open = update(this.stats.open);
      case PositionState.Closed:
        return this.stats.closed = update(this.stats.closed);
}
```
So if a new value would be added to `PositionState` the compiler would complain about function `updateStats` may return `undefined` while its return value is explicitly set to `number`. As an option, `number` can be changed to `true` when each branch would `return true`.
___
*[src/exchange/positions.ts, line 118 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJMzuD5WwbP9pgbMBA:-MvJMzuD5WwbP9pgbMBB:b-1bv7wr) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L118)):*
> ```XML
>     const { positions } = this;
> 
>     return _([...positions.entries()])
> ```

It seems that native `filter` and `map` would work the same here
```ts
return [...positions.entries()]
  .filter(([_address, info]) => info.state == PositionState.Open)
  .map(([address, _info]) => address)
```
or even
```ts
return [...positions.entries()]
  .flatMap(([address, info]) => info.state == PositionState.Open ? address : [])
```

**Comment by Alexsey** [comment]
*[a discussion](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvKAOi22zNajehiAYv7:-MvKAOi22zNajehiAYv8:bl060ej) (no related file):*
In general, it's really great that CLI functions have been refactored!

---

**Review by ilya-bobyr — COMMENTED** [review]
> Dismissed @Alexsey from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/28)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @Alexsey)

*[a discussion](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvKAOi22zNajehiAYv7:-MwOOojyDJQHMzZY5X3V:b-896fix) (no related file):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

In general, it's really great that CLI functions have been refactored!
</blockquote></details>

Done.

---
___
*[src/exchange.ts, line 217 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJS2fE76yhcFEt-ipN:-MwOOr7G6a9pAFNNnx4q:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange.ts#L217)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

`default_` seems redundant here - changing below to `{ default: deployment.launchBlock }` would look even more informative
</blockquote></details>

Done.
___
*[src/config/deployments.ts, line 1 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIkRw37_yjA3pW3EwE:-MwOPk7q7wYVjsu9Fwci:b1teyli) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L1)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

What is the reason for constructing this config half-programmatically and half-manually? It really looks like that simple structure, like the one that has been used before, would suit much better
```ts
export const deployments = {
  RINKEBY_ARBITRUM: {
    ETH_USDC: {
      exchangeAddress: "...",
      launchBlock: 123,
    },
    ....
  }
}
```
Just ensure `Deployments` to have methods `get` and `addresses`. And yes, the presence of `get` method seems like an opportunity to use pairs names as keys, that are simpler and more representative then addresses (would look much nicer in logs).
</blockquote></details>

Addresses can be written using different casing.
As we use addresses as keys, we need to choose one way to represent addresses.
There is no value in failing to find a deployment, if the address is written using all lower case, or if the address has the checksum embedded in the letter casing.
This detail is not important for the configuration, and I hide it in the class constructor and the `get` method.

Adding names for the deployments is indeed nice, but is outside the scope of this change, I think.
___
*[src/config/deployments.ts, line 10 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIq-_M5DclgCVBv2yi:-MwOT7JQ-1R6ndmofrEu:btdi4oc) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L10)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

Looks like this can be a simpler `type` instead of `class`.
</blockquote></details>

This would remove type information from run time.
Types do not have associated functions, so I would need to make `get` and `addresses` free functions.
I think `class` is a better choice here.
___
*[src/config/deployments.ts, line 26 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvImEh4-DXmh30-0LCp:-MwOSG3m6HroBvozN5zw:bq2loqp) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L26)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

It's always preferable to use plan object instead of `Map<string, whatever>` as one is more basic and much easier to work with data structures.
</blockquote></details>

While it might be true in many cases, in this particular case it was the opposite.
I had to write a bit more code to use a general purpose Object as a map.
___
*[src/config/deployments.ts, line 41 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvImIpU5Qo-Uc_ZPGTA:-MwOTqIU7ah-TgqPrsa9:b-896fix) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L41)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

This is the same as `return this.deployments.keys()`.
</blockquote></details>

Done.
___
*[src/config/deployments.ts, line 46 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIn70s1HRBiZR0sR8x:-MwOU60x7Odl1AoBSS8p:b-7qrabe) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/config/deployments.ts#L46)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

It's better to avoid setting a type here - TypeScript itself would produce a better more specific type with keys limited to the actual values you've used. Unless you want it to be more generic with `string` as a key on purpose.
</blockquote></details>

An explicit type serves as both documentation, explaining the intent, and helps find errors.
An implicit type would just be inferred from whatever I write below, even if it is incorrect.
I think top level definitions should all have explicit types.

If I could be able to avoid just the `string` part of the type, that might be an interesting option.  But I could not find a syntax for that?
___
*[src/exchange/positions.ts, line 13 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIoxpU-GQq2riQQx4s:-MwOUwJ--5SGUMRPHiM8:b-tb9y80) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L13)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

```ts
type PositionState = Brand<"open" | "close", "positionState">
```
or IMHO absolutely good enough as for a non-public type
```ts
type PositionState = "open" | "closed"
```
would be a simpler structure that would feet the needs as well as `enum` but without adding any code to the runtime
</blockquote></details>

Enum is a number.

```typescript
type PositionState = "open" | "closed"
```
is a string.

I am not sure the argument about adding code to runtime is applicable here, as string are less efficient.
At the same time, optimizing this enum is unlikely to provide any value.
So, the choice should be more based on code readability.

From my standpoint, an `enum` seems like a better match.
Both of the options you suggested look like workarounds for the absence of a dedicated enum type.
___
*[src/exchange/positions.ts, line 18 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvIoVNz1Pv4jtW-O5pW:-MwOUoHS8xRD0rV7-Gk2:bt284fp) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L18)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

It looks like this can by `type` instead of `class`.
</blockquote></details>

I disagree that this is a good thing.  It removes the type from run time.
Meaning it could be harder to debug.  And it can not have methods.
___
*[src/exchange/positions.ts, line 40 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvInzNb8OGli1R3FOwn:-MwOXV-p3nTVo1Ym287H:b-cmpqal) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L40)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

It's always preferable to use a plan object instead of `Map<string, whatever>` as one is more basic and much easier to work with data structures.
</blockquote></details>

I've switched to an `Object`, but I disagree here as well.
I had to write slightly more code, and it seems to obscure the intention, as I really want a `Map` here.
___
*[src/exchange/positions.ts, line 110 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJKG7t9i5QcwAeLH_Z:-MwOXzc-7tuuVe0SdibT:buunjpc) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L110)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

Currently `default` branch is impossible. I assume that you've added it in case of other possible values would be added to `PositionState`. You can ask the compiler to give an error if `PositionState` would be extended without adding a `case` to handle that new values. There are two ways to do this: first is a more general pattern that would allow to left `updateStats` signature as is (exhaustive switch), but I think we can go have with a simpler one
```ts
private updateStats(...): number {
    state: PositionState,
    update: (counter: number) => number
  ) {
    switch (state) {
      case PositionState.Open:
        return this.stats.open = update(this.stats.open);
      case PositionState.Closed:
        return this.stats.closed = update(this.stats.closed);
}
```
So if a new value would be added to `PositionState` the compiler would complain about function `updateStats` may return `undefined` while its return value is explicitly set to `number`. As an option, `number` can be changed to `true` when each branch would `return true`.
</blockquote></details>

`updateStats` has no return value.
Relying on the return value type mismatch seems fragile.
And changing the `updateStats` return type to something that is not `void` just to avoid a `default` clause, does not seem right, either.
Callers should not be affected by the function implementation.

As TypeScript does not have exhaustiveness checking for the `switch` statement, it seems reasonable to write `default` clauses.

There is an eslint check that can be used for this: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
But we need to enable it first, before we start writing code in this way.
___
*[src/exchange/positions.ts, line 118 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/28#-MvJMzuD5WwbP9pgbMBA:-MwOX7CR2pyMJA_B2mD3:b-afmt2t) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/bf8e17149632faf979b7667255303fe9681b6a9d/src/exchange/positions.ts#L118)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

It seems that native `filter` and `map` would work the same here
```ts
return [...positions.entries()]
  .filter(([_address, info]) => info.state == PositionState.Open)
  .map(([address, _info]) => address)
```
or even
```ts
return [...positions.entries()]
  .flatMap(([address, info]) => info.state == PositionState.Open ? address : [])
```
</blockquote></details>

Used native `filter` and `map`.
`flatMap` seems less readable.

**Comment by ilya-bobyr** [comment]
I'll merge this PR, but I will make any changes, if we decide that this review is incomplete.

**Pull request merged**
