### PR TITLE
Uniswap incentives: Use bigint

### PR DESCRIPTION
**Pull request by ilya-bobyr**
Numbers cause rounding, which in turn causes problems with precise token allowances.

---
This change is [Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30)

### CODE REVIEW

**Review by gerben-stavenga — COMMENTED** [review]
I only see verbose added

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-:-MwOmn2p3z9R05FbaZ-M:b-m6tqzn)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Alexsey, @kienswap, and @maxibustos)

**Review by ilya-bobyr — COMMENTED** [review]
I've set the default to be per-commit review, rather than the full PR diff.
Maybe this setting affects everyone, not just me?
But, you can click "Show full diff" at the top to see the whole branch diff.

`r1` and `r2` in the file matrix are two commits that are in this PR.
So, alternatively, you can switch viewing range in the File Matrix.
Looking at just the first, just the second or both commits together.
The first commit adds the `verbose` flag, and the second changes types to `bigint`.

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-:-MwPgK2CAASq7QihZwaY:b-axnhh3)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Alexsey, @kienswap, and @maxibustos)

**Review by gerben-stavenga — COMMENTED** [review]
I see nothing but boolean verbose flag

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-:-MwPul-95eInmT-AuQ6w:bvdxavx)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Alexsey, @kienswap, and @maxibustos)

**Review by gerben-stavenga — COMMENTED** [review]
oh somehow uniswap was completely not selected. hmm okay

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-:-MwPuuZlE3LL8CvS7QXW:bf7ujja)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Alexsey, @kienswap, and @maxibustos)

**Review by gerben-stavenga — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-:-MwPvG561N6kFfE93B-V:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Alexsey, @kienswap, and @maxibustos)

**Review by Alexsey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ilya-bobyr, @kienswap, and @maxibustos)

___
*[src/uniswap/incentives.ts, line 31 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-MwSAwDvD-uiYzBFsp_g:-MwSAwDwAq3hkdUoyg7Z:b-jzr76a) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/388675b370cc09edac0d90a358ef49b33054c64c/src/uniswap/incentives.ts#L31)):*
> ```XML
>   constructor(
>     /**
>      * First moment in  distribution covers.
> ```

double space between "in" and "distribution"
___
*[src/uniswap/liquidity.ts, line 988 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-MwS8pp-AglFDi3I3Rzx:-MwS8pp-AglFDi3I3Rzy:b-ax9pwv) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/a0dc280cd7f3ec16ea6775f090a5c6a421038290/src/uniswap/liquidity.ts#L988)):*
> ```XML
>       return provider.getLogs(allEventsFilter);
>     });
>     if (verbose) {
> ```

I REALY don't like that we are going to do such things in code. It should be handled by the logger configuration and not by an if statement. I will not block this change but the fact that we are doing this is a very clear sign that we need to move from `console.log` to use some logging library that allows configuration

**Review by ilya-bobyr — COMMENTED** [review]
> Dismissed @Alexsey from a discussion.
> *[Reviewable](https://reviewable.io/reviews/futureswap/fs-cli-v4/30)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Alexsey, @kienswap, and @maxibustos)

___
*[src/uniswap/incentives.ts, line 31 at r2](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-MwSAwDvD-uiYzBFsp_g:-MwduIuwDFwqCCnrYe3C:b6ehxu3) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/388675b370cc09edac0d90a358ef49b33054c64c/src/uniswap/incentives.ts#L31)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

double space between "in" and "distribution"
</blockquote></details>

I've accidentally deleted two words in there.
Fixed, thank you.
___
*[src/uniswap/liquidity.ts, line 988 at r1](https://reviewable.io/reviews/futureswap/fs-cli-v4/30#-MwS8pp-AglFDi3I3Rzx:-MwduNdT9GhoGuEaYXBR:bi1ak0j) ([raw file](https://github.com/futureswap/fs-cli-v4/blob/a0dc280cd7f3ec16ea6775f090a5c6a421038290/src/uniswap/liquidity.ts#L988)):*
<details><summary><i>Previously, Alexsey (Aleksey Bobyr) wrote…</i></summary><blockquote>

I REALY don't like that we are going to do such things in code. It should be handled by the logger configuration and not by an if statement. I will not block this change but the fact that we are doing this is a very clear sign that we need to move from `console.log` to use some logging library that allows configuration
</blockquote></details>

I agree that going forward, we may consider using a logging library.
As there are only 2 messages that I wanted to silence and this is a CLI tool, I think, it is OK to use `console.log` directly, passing the `verbose` argument around.
Should we see more of this pattern, we may consider connecting a library.
In practice, there is a chance, today is the last day we are running this tool.

**Pull request merged**
